name: GitHub build docker

on:
  push:
    branches:
      - master

jobs: 
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true # push to registry
          pull: true # always fetch the latest base images
          platforms: linux/amd64,linux/arm64 # build for both amd64 and arm64
          tags: ghcr.io/niek/obs-web:latest