name: GitHub build pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and deploy GH pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v5 (master)
        uses: actions/checkout@v4
        with:
          ref: master
          path: v5

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build v5
        run: cd v5 && npm ci && npm run build

      - name: Make a single folder with v4 and v5
        run: cp -r v5/public .

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
